baseURL = 'https://www.foxhollow.cc/'
languageCode = 'en-us'
title = 'Infrastructure and Linux Enthusiast | Steve Cross'
theme = "m10c"
enableGitInfo = true
buildDrafts = true
timeout = 120

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'fruity'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about-me"
    weight = 20
    # [menu.main.params]
    #   icon = "user"

  [[menu.main]]
    identifier = "homelab"
    name = "Home Lab"
    url = "/tags/home-lab/"
    weight = 30
    [menu.main.params]
      break = true
    #   icon = "server"

  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    weight = 40
    [menu.main.params]
      break = false
    #   icon = "server"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 50

[[menu.main]]
    identifier = "media"
    name = "Media"
    url = "/media/"
    weight = 60
    [menu.main.params]
      break = true
    #   icon = "server"

  [[menu.main]]
    identifier = "tags"
    name = "All Tags"
    url = "/tags"
    weight = 100
    # [menu.main.params]
    #   icon = "list"

[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'

[params]
  author = 'Steve Cross'
  header_title = 'Steve Cross'
  description = 'Infrastructure and Linux Enthusiast'
  subtitle = 'meow?'
  avatar = 'profile_photo.png'
  # menu_item_separator = '<br />'
  menu_item_separator = '-'
  keywords = ['Steve Cross', 'hairlesshobo', 'foxhollow', 'self hosted']

  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/hairlesshobo"

  [[params.social]]
    icon = "linkedin"
    name = "Linkedin Profile"
    url = "https://www.linkedin.com/in/steveacross/"

  [[params.social]]
    icon = "sunset"
    name = "Astrobin"
    url = "https://www.astrobin.com/users/hairlesshobo/"

  [[params.social]]
    icon = "radio"
    name = "Amateur Radio Site"
    url = "https://www.kn4goi.net/"

  [[params.social]]
    icon = "tokenring"
    name = "The Token Ring webring"
    url = "https://tokenring.monoxane.io/#foxhollow"

  [params.style]
    darkestColor = "#050a10"
    darkColor = "#081016"
    lightColor = "#bbc0ca"
    lightestColor = "#e79755"
    primaryColor = "#e17e2d"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 1
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 100

  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
    
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 80

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

