baseURL = 'https://www.foxhollow.cc/'
languageCode = 'en-us'
title = 'Steve Cross'
theme = "m10c"
enableGitInfo = true

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 100

  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
    
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 80


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about-me"
    weight = 20
    # [menu.main.params]
    #   icon = "user"

  [[menu.main]]
    identifier = "homelab"
    name = "Home Lab"
    url = "/tags/home-lab/"
    weight = 30
    # [menu.main.params]
    #   icon = "server"

  [[menu.main]]
    identifier = "tags"
    name = "All Tags"
    url = "/tags"
    weight = 40
    # [menu.main.params]
    #   icon = "list"

[params]
  author = 'Steve Cross'
  description = 'Infrastructure and Linux Enthusiast'
  subtitle = 'meow?'
  avatar = 'profile_photo.png'
  menu_item_separator = '<br />'

  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/hairlesshobo"

  [[params.social]]
    icon = "linkedin"
    name = "Linkedin Profile"
    url = "https://www.linkedin.com/in/steveacross/"

  [[params.social]]
    icon = "sunset"
    name = "Astrobin"
    url = "https://www.astrobin.com/users/hairlesshobo/"

  [[params.social]]
    icon = "radio"
    name = "Amateur Radio Site"
    url = "https://www.kn4goi.net/"

  [[params.social]]
    icon = "tokenring"
    name = "The Token Ring webring"
    url = "https://tokenring.monoxane.io/#foxhollow"

  [params.style]
    darkestColor = "#050a10"
    darkColor = "#081016"
    lightColor = "#bbc0ca"
    lightestColor = "#e79755"
    primaryColor = "#e17e2d"

[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'